import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Hacktoon Next Js App",
  description: "Generated by Syed Muhammad Shan -e-Ali",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
